### ISSUE TITLE
Add instructions on how to get this fork working with other languages ex. PHP

### ISSUE THREAD

**Issue by derrickschoen** [btmills/prettier#1]
I ran
$ yarn add -D prettier@npm:@btmills/prettier
$ yarn add -D @prettier/plugin-php

$ node_modules/.bin/prettier testp.js  -> the operators are at the beginning of the line

$ node_modules/.bin/prettier --config=prettier.config.js --parser=php testp.php -> the operators are still at the end of the line

Is this something you can help with or should I take it up with the plugin authors?

**Comment by Yurickh** [comment]
Hi derrickschoen! 👋 

I wonder what happens if you run `yarn prettier testp.php --write`. 
Is that something you could try?

**Comment by derrickschoen** [comment]
> Hi derrickschoen! wave
> 
> I wonder what happens if you run `yarn prettier testp.php --write`.
> Is that something you could try?

@Yurickh Thanks for the reply! 
I tried 
```
yarn prettier testp.php --write
```
but, unfortunately I got the same results:



```
<?php

$uri = urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));

function testp($uri)
{
if ($uri === 1 ||
$uri === 2 ||
$uri === 3 ||
$uri === 4 ||
$uri === 5 ||
$uri === 6 ||
$uri === 7 ||
$uri === 8 ||
$uri === 9 ||
$uri === 10 ||
$uri === 11 ||
$uri === 12 ||
$uri === 13 ||
$uri === 14 ||
$uri === 15 ||
$uri === 16 ||
$uri === 17 ||
$uri === 18 ||
$uri === 19) {
return false;
}
return true;
}

testp($uri);

```

--becomes--

```
<?php

$uri = urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));

function testp($uri)
{
    if (
        $uri === 1 ||
        $uri === 2 ||
        $uri === 3 ||
        $uri === 4 ||
        $uri === 5 ||
        $uri === 6 ||
        $uri === 7 ||
        $uri === 8 ||
        $uri === 9 ||
        $uri === 10 ||
        $uri === 11 ||
        $uri === 12 ||
        $uri === 13 ||
        $uri === 14 ||
        $uri === 15 ||
        $uri === 16 ||
        $uri === 17 ||
        $uri === 18 ||
        $uri === 19
    ) {
        return false;
    }
    return true;
}

testp($uri);

```

**Comment by Yurickh** [comment]
Unfortunately, due to the php printer being in its own plugin, you'd have to fork the plugin as well, and change the printer to not break the line after operators, rather before them.
I'm not familiar with the codebase, but if I had to guess, I'd check the core around [this point](https://github.com/prettier/plugin-php/blob/master/src/printer.js#L1492) to do the change.

**Comment by btmills** [comment]
@Yurickh is likely correct - this is probably something that needs to be changed in the PHP plugin. I skimmed the PHP plugin's [`printBinaryExpression()` implementation](https://github.com/prettier/plugin-php/blob/66ae12f85f3b3894f4c420924e1da1aaa4f52df7/src/printer.js#L759-L837) and it looks like they're handling newlines differently than the [JS version](https://github.com/prettier/prettier/pull/7111/commits/5dce7e13d172d1b638e3698078d17fc30f8981ab). Sadly I didn't see a `lineBeforeOperator` variable that provided an obvious hook point.

If you figure out how, feel free to adapt the [release steps](https://github.com/btmills/prettier#releases) from this repository that I follow to keep the fork's change rebased on top of the latest Prettier release. And if you end up releasing your own plugin fork to do this for PHP, let me know and I'll add a link to the Readme so other PHP users can find your forked plugin.
