### ISSUE TITLE
README should be updated with instructions for yarn v2 (e.g. berry)

### ISSUE THREAD

**Issue by Zamiell** [btmills/prettier#13]
As advised in the README.md file, doing a:
`yarn add -D prettier@npm:@btmills/prettier`
results in the following error when using the latest version of yarn/berry:

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: prettier@npm:@btmills/prettier isn't supported by any available resolver
    at i.getResolverByDescriptor (D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:314703)
    at i.bindDescriptor (D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:314068)
    at D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:337379
    at async Promise.all (index 0)
    at async Ae.resolveEverything (D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:336702)
    at async D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:353870
    at async C.startTimerPromise (D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:364798)
    at async Ae.install (D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:353504)
    at async D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:66854
    at async Function.start (D:\Repositories\test2\.yarn\releases\yarn-berry.cjs:2:363929)
```

After some trial and error, I discovered that this can be fixed by instead adding the following line to `devDependences` in the `package.json` file:
```
"prettier": "git+ssh://git@github.com/btmills/prettier",
```
(I'm not sure how this would translate to a `yarn add -D [foo]` command.)

Hopefully this information can make it into the README in one form or another.

Furthermore, it would be fantastic to put instructions in the README.md for getting it working with `npm` as well, for those people who don't want to use `yarn`.

Thanks for the excellent fork btmills. <3

**Comment by btmills** [comment]
Hi @Zamiell :wave: can you give this another shot? I don't use Yarn v2 myself, but I just tried it out and didn't hit any issues. Hopefully a recent release fixed whatever was wrong a month ago and this now works with the same install command as yarn v1 🤞

```
$ mkdir prettier-test
$ cd prettier-test
$ yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into prettier-test/.yarn/releases/yarn-berry.cjs...
Updating prettier-test/.yarnrc.yml...
Done!
$ echo '{ "private": true }' > package.json
$ yarn add --dev prettier:@npm:@btmills/prettier@^2.2.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 286ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @btmills/prettier@npm:2.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 435ms
$ yarn bin prettier
prettier-test/.yarn/cache/@btmills-prettier-npm-2.2.0-25c752a7a6-8e4ea21e85.zip/node_modules/@btmills/prettier/bin-prettier.js
$ yarn run prettier --version
2.2.0
```

**Comment by Zamiell** [comment]
Hey btmills, thanks for taking the time to reply, and sorry for my late reply.
I never got the chance to test, and since I opened this issue, I have stopped using Yarn entirely (in favor of using plain npm, as it is just a lot simpler and has gotten better recently), so I'll go ahead and close this issue now since it sounds like it is probably resolved.
