### ISSUE TITLE
How about a Prettier plugin instead of a fork?

### ISSUE THREAD

**Issue by Zamiell** [btmills/prettier#16]
Hello btmills,

Thanks for your work on this excellent fork.

Using this fork with a team can be tricky. I get asked questions like:

"Hey Zamiell, I'm down to use Prettier, but why we are using some unofficial fork of Prettier instead of the official version?"

And then the discussion turns to a cost-benefit analysis of:
- Pros: Having superior prefix operators.
- Cons: Having the fork be out of date and/or divergent from the official Prettier codebase, having a fork be more vulnerable to security issues, and so on.

Recently, I have started using the excellent [`prettier-plugin-organize-imports`](https://github.com/simonhaenisch/prettier-plugin-organize-imports), which makes Prettier neatly organize the imports at the top of the file. In particular, it's really easy to use because it requires no configuration - all you have to do is install the dependency in your package.json file and Prettier automatically picks it up - no changes to linting/CI/whatever are needed! And conversely, when you want to stop using it, it is as easy as simply removing the dependency.

I envision a world in which this fork could exist as a plugin instead. In that world, people could simply install it for a no-configuration change to get prefix operators in their projects. And then, in the future, when Prettier 3.0 is released (hopefully within the next 5 years, but who knows ><) and the real Prettier has prefix operators, then end-users can simply get rid of this dep for a super-easy transition process.

Another benefit of having a plugin is that it is an easier sell to people on a team, because you still use the official Prettier instead of a fork.

It's also much easier maintenance-wise for you / whoever the maintainer is, because the fork doesn't have to stay up to date every time Prettier releases a new commit.

Do you think this idea is viable? Are there any downsides that I am not thinking of?

**Comment by Yurickh** [comment]
The problem I can see with prettier plugins is that they are designed to add new languages, not extend the existing ones. What [prettier-plugin-organize-imports](https://github.com/simonhaenisch/prettier-plugin-organize-imports) does is smartly override the default language parsers with an extended version of them, you can see this happening at the [very end of their main file](https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/master/index.js#L79).

This means that two plugins will never be able to co-exist at the same time, the second one will always override the first. So even if they do seemingly isolated things -- sorting imports and placing operators, for example --you will only get one of them.

This unfortunately is how prettier works in its own philosophy -- it's supposed to be a strongly opinionated parser and have little to no configuration exposed, plugins included.

So unless prettier adds an official API for parser extension, I think the fork is unfortunately "the way" of doing it.

**Comment by Zamiell** [comment]
That's unfortunate, I didn't know about that limitation. =(
