### ISSUE TITLE
Update upstream

### ISSUE THREAD

**Issue by sxxov** [btmills/prettier#17]
[`prettier/prettier`](https://github.com/prettier/prettier) is currently on v2.8.1, which supports new TypeScript features & formatting improvements. While https://github.com/prettier/prettier/issues/3806 is in the milestone for v3.0, having a patch to ease through before v3.0 would be really helpful.

**Comment by isaacl** [comment]
how annoying is it that this fork is STILL required

**Comment by btmills** [comment]
Just published versions up to 2.8.4! https://www.npmjs.com/package/@btmills/prettier/v/2.8.4

**Comment by sxxov** [comment]
thank you for all the effort on this fork!
