### ISSUE TITLE
prettier crash with TypeError: P.splice is not a function

### ISSUE THREAD

**Issue by mat813** [btmills/prettier#19]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEFsAbMiAYTNQRgBoTzKAZVKAaybBzgEN4ACRgxM7LkwCSUALJx0uAJ5V+YABZwmAZ0y0CAX3wAzHBHT4A5AAF+LCAHowtek9xxLAbgA6UDNjxCfF4BeAAFOBxtVG14ABMARQBXSKUJTnwjU3MrW3snF1gHWi4HTEjo2Lg4gFoARxScOm0vX39cAiIAcRw7dQTWAHVtdMyTMwsbOwgKR2c6IpLOB20kgCNtXlRMGFRoFp8-LA6ggHM4GFl+DgAROGMOVF3oMezJvJnKAoWYByTd-TNVpHAKdfAAZXU-AATABWABsrwmuX4AHdtDVeEodo5tFC4fCamszOjIsD2oEiHdjPwkmQYKRPtRCoZxjkbAA3FIOaazTHmbDafhrMgeQ4UsEAaQ4cSYAHlyr1nlAACrYuAAOQgcTgSPZp16mHUdTI5OOlOCfEEcBoPz1kwNfRNNXRZtB+Bg6qCpEw9qsXLFvja5rBlDA-DIxH+6j9NjKZCSpw42h50bdJ1pMHU4MiHNQYF1b1y8cTydTWYAdNpc-nA1Bg+61vxq3c1om2ZMKw4dW3TsDfJAoLF8D32wBefBNltwXsVuAAD3gUDiAApLLzKJYAJSHXwOBz4IQqlVhYLQKBwMDKj0QD2aEhhKQD-YEdSicQcDITkLWkRidIrsAvj4Pg+74AAmhAST4HiUFkHE+BJNW+D8FAKEbDM-y6gAqgASqw+CaHwwGIU0SD4AABgAJMAEoVugFz8HOUAchWABqUgqgAogA+sQj48QAQsQVCSlxGo3AYNF0QxMBMQgrEcdxfECV0uH8UIAwGBRDC+AYO5BlAg7DksVBQhw+Dfla4QVDE8TJKkAFAWhMH4gi5HNkoRn4CuDSpORsRNFApxbuRYQTDEcAADyBRwpwAHyWYlzkgSBxkEHi-CWfgF6ohCbnwiuBkuSBmUVkkmBxNavmNEoxWpWeQ4EHEqDnMOE5otcGVQhWLVtTARW7iV+B8DASQ4GhfVwLEFZ8HESQFiuJENSumB8HmUHaEwHAwFuSXLQ1+BrXAG1IQdDUOAAVOdDWXfgVC6uUuwEGsUEEGQAAHR18MuiFofQdA4PgAAck5PFt+Cih6vRDsYuAMfgCDBFCAB3F4jnAN2pXd4a9FeAAXfAQxcMHrtoqx8PgfmQ7qOAAJerPSggmF1YNI9CwT8HjMCE9NiP1sNh13fwABWb2oQQSRoQADCh0FxHTbYZagk7TRAHAVljIGXQ4WsANT4DtFYwBA4IwEFpwrgAjPCW4Vpg-BxGbXMDdCTCWNL266YLViWAd9WZN7+lDWBqgaLq-iigxsCCHsAvpZz4fZbl+AyPIig4CoaiaIBJGeuUYQzPmzTkSlqVgcQYtYUDxc09oHrqvXcTQO9lhSDcOW6i0djlBQj3NpRqBxBRJEGEHxXPk1ctZrIQ9xKKqJc7qE4p4yswASuECKrH0BMHDOCLzgcR7WOyUkWBjsIVmuqZuouCoAAXjvaEm3euqaI7FQkQnawCHwQMdWjDmHAeYCzGwgJwBAQ0QKoGMD5X+S8AFjgnFLHUDwLzH0IAdUclt1zRlnnEeecBD5wHIlAW8JtIFQG3IcECRg4BkGQmXECooCC33vk-a8E4KKCT-pEfANEEH-20tA1KOC1y3wIUQkh5FKEIHIgAUggJYJgQjIgT2GrAnyYYIxRkrGAcaPEDGxHMJEHiQ9LLIL+mgjg1Q9rMLETORMEj8FzwXkvMht4qDjW8bEKQcQaEHXoYw3UDiQLiLwTPNxxCPH3R8UhGA-jFHKKYDoyM0YKwGJwEYhJpjslDwDg1dhTROFx3wHrbhcScC+MSXEJANE0l6PUJkwxxiTYMXyXEERQTDINS3pEZ+VYLhUBbguAaYTCICB1FEUuWtimP2ft7Q6gcgkBwML0kaFxxpoX3ofVc-SlRx2KsHQyCd0SjBXsQ-APQ+gDGGABb+1kbQslzsNcaZByLUVoiGeijFmKKU4rxfiUgeKDHBMJUS4lJLSR+bJeSLF2KApUiC8E2FBLgioLhKQYQVRSDlBqcE2lZpwD0GoOAK4HAAD03xiAcO7V0W5vYHTIPwB+ShyI0hCUy4a0AtRQFYKypQXEcBmBwCuSIor7E3Qiby6AAq2XCtFcklRiMRW4EKSsgWDVBwXivHHMIXN+DoG0EVLBPsf58IAdPbMNYwFyKgKIhqWiVxqKQSg5c9xbGYImeEpxuCdWXmVAa3oskKieJvFQwJPtglMK1qw61HDn7ZR4ZagRwBXXdK1csjGvY1wBr1dAYNRqLhhojfI-ASiVWuo0dmw2cCVyNIyVknJJiOnmIQsg91NiMFSp9g1CJ+ag2GtDTMnKXj4l+ICRqhqMbQlaxAvM0pLwKmUSqTUpJDSIDhnSfo1puS21D0zbW31ubLCDv1cOkto7vHVISUkitKTIZbt0U2vdrazEFNodm9ZWblmjW2Wa49JBoyJuVB5EDJTFlawMF+mdGyGr-omoQGDQSlmZC3L4DRV1gJ3RVPeXQ+gTBSwLS-fgkD65Zj4P3ENV7tBIBwzh-Ad1iBEaMteLMghLD123aKBC+9EbZ3wAcpNr8FyXiwox3D95RivyQoWXAKE0LCevFo6+rGSObLGhNeuWVvAgHNtGJQen8AcgjCkST+A8O6hk7eOTJgFOoSE9vFTcC1PGGI9eRDQ4UL4D05y7QRmQAmbM5jNCOtJ7DgI08C5ME9BPCWi5QCVNaroaSoB1KCdu1PDKROc4lxrhQGpI8ZUNVUg1scaeqLMB0jkSy2Bh9Kq6tHMdZpgDTXoAVk4DKSxE5pTLgrHKMIXF1K4vxTxG4XEABiUgNScTxRqfAAAyRbGN0HZY68pnLViFQDOVGqcoWodQVlReizF2LRsai-WPEi5zPxobAtNEoMAagtSFCKOANQLyLhqCUXUUt8y4CgGUPgxhIg1F0FaOIJFJHRJIZk6A4YBqmXMlAO2g5EcrhpR+LgGHUchwPFQJ5b8UL2GCCyXwC53QJw3MyO0ly8pr0oLaegryWGfgCnF6rd3v7nkDSqCAdwOT85mHR6GKQ0PhnDuPIalOThoNpPSdLnlvLJjkhQFcPdyI+lCvgcK5hIpRQ5OrOIZ9hoRNVxGU0Gqe72zMHmHUK5qQK4ZPYZnsAmA07d7tK7QdDggAYCALeyptDIFAFzEkwaEAh5QBGReSgQ8B+JGoSBMBwTFokHAZA-mtAgCT2AFP4IHZgDisgAzOfqzoFQKXnA4uQDRGCqKZIEB4BZ4jNWAPIttDznBHFRvSRm+Z6QNngPDQB968wNHkAzZPtwGqNUf3+neioBKKcEZ6B0D8GQFPigC-6+nFFMQUQTQlZwAiDgDPreuUgDfOgMggx1BPGmkXuAOYhzZbzJ6LfYByYL4DDIHUsA4IWwOwxAy4ZsSgool+7eIAa0EA1YgwhoW+x01YICmeAeyYkQMA4U-ApwG+UBOeDsUQkQW++c00wBMAC+a0O0gwQ8WYyAwM0sAefADQqAfA2BuBm+Q+beOeckawNBcQdBSAbsIAcmKowo0ew+IACgv8hC1QAqwUSQOBcAk28MgguwwUW+mYEAIABgBgQAA)

```sh
# Options (if any):
prettier --log-level debug /home/mat/work/si-client/ui/src/plugins/apollo.ts
```

**Input:**

see playground

**Output:**

```
$ prettier --log-level debug /home/mat/work/si-client/ui/src/plugins/apollo.ts
[debug] normalized argv: {"":["/home/mat/work/si-client/ui/src/plugins/apollo.ts"],"cache":false,"color":true,"editorconfig":true,"logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":["/home/mat/work/si-client/ui/src/plugins/apollo.ts"],"__raw":{"_":["/home/mat/work/si-client/ui/src/plugins/apollo.ts"],"cache":false,"color":true,"editorconfig":true,"log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] resolve config from '/home/mat/work/si-client/ui/src/plugins/apollo.ts'
[debug] loaded options `{"trailingComma":"es5","arrowParens":"always","endOfLine":"lf","printWidth":120,"singleQuote":true}`[debug] applied config-precedence (cli-override): {"singleQuote":true,"arrowParens":"always","trailingComma":"es5","endOfLine":"lf","printWidth":120}
src/plugins/apollo.ts
[error] src/plugins/apollo.ts: TypeError: P.splice is not a function
[error]     at ts (file:///home/mat/work/si-client/ui/node_modules/prettier/plugins/estree.mjs:18:4598)
[error]     at Or (file:///home/mat/work/si-client/ui/node_modules/prettier/plugins/estree.mjs:18:2789)
[error]     at xi (file:///home/mat/work/si-client/ui/node_modules/prettier/plugins/estree.mjs:28:18376)
[error]     at gc (file:///home/mat/work/si-client/ui/node_modules/prettier/plugins/estree.mjs:28:34997)
[error]     at Object.Sc (file:///home/mat/work/si-client/ui/node_modules/prettier/plugins/estree.mjs:28:35405)
[error]     at callPluginPrintFunction (file:///home/mat/work/si-client/ui/node_modules/prettier/index.mjs:18140:20)
[error]     at mainPrintInternal (file:///home/mat/work/si-client/ui/node_modules/prettier/index.mjs:18123:18)
[error]     at file:///home/mat/work/si-client/ui/node_modules/prettier/index.mjs:18111:29
[error]     at AstPath.call (file:///home/mat/work/si-client/ui/node_modules/prettier/index.mjs:17265:14)
[error]     at mainPrint (file:///home/mat/work/si-client/ui/node_modules/prettier/index.mjs:18111:18)
```

**Expected behavior:**

Tested with prettier@3.0.0, it does not crash.

**Comment by btmills** [comment]
Fixed in [`3.0.3-fork`](https://github.com/btmills/prettier/releases/tag/3.0.3-fork)!

The minimal repro is https://github.com/prettier/prettier/commit/1ec64484fc76838617d9840cc88b692250308336#diff-a1337b1f9e125e53fe089bff0b7722d92f9edb4c73acff53d1c32016668afdc1R1-R3, and the fix is https://github.com/prettier/prettier/commit/02c497e8e39e4d4ccb06fedab239e65c3ad4551b#diff-4cc7e3603f38395d747c5b63668c3518312040765007f0e30d9fcc6f2cf82c6eR282-R289.
