### ISSUE TITLE
option to set && || at new line

### ISSUE THREAD

**Issue by zuhairtaha** [btmills/prettier#2]
I always install this package [@btmills/prettier](https://www.npmjs.com/package/@btmills/prettier)
to move binary operators to the beginning of new lines in long expressions instead of the end of the previous line
and hope to have an option at prettier instead of using updated package
It might be at `.prettierrc` like this
```json
{
   "operatorsAtBegining": true
}
```

**Comment by btmills** [comment]
I'm glad this is useful to you! Like you, I'd prefer to have this in Prettier itself if the Prettier team is willing. There's an open issue in the main Prettier repository requesting this change at https://github.com/prettier/prettier/issues/3806. I opened a pull request to incorporate this fork's change into Prettier at https://github.com/prettier/prettier/pull/7111. Please go leave a :+1: on both. Hopefully with enough support the Prettier team eventually agrees to merge the change.

**Comment by btmills** [comment]
I should also note that the Prettier team is generally reluctant to add options, so I implemented the pull request as a change to the default without an option. I'm hoping that improves the odds they accept it. There's been some discussion in the issue of doing it with an option instead, so if the team decided they prefer that, I'd be willing to implement that too.
