### ISSUE TITLE
Prettier Plugin Api

### ISSUE THREAD

**Issue by ricklove** [btmills/prettier#20]
Is it now possible to implement this as a plugin with the prettier plugin api?

https://prettier.io/docs/en/plugins

**Comment by ricklove** [comment]
Ah, nevermind: https://github.com/tailwindlabs/prettier-plugin-tailwindcss?tab=readme-ov-file#compatibility-with-other-prettier-plugins

**Comment by isaacl** [comment]
@ricklove I don't understand -- why did you close this?  Is it not supported by plugin api?

**Comment by someonewithpc** [comment]
Agreed @btmills please reopen this, and if you want help tackling the transformation, lmk
